version: "3.3"

services:
  bot:
    build: "./"
    restart: always
    volumes:
      - /var/NeoPostAdminBot:/var/NeoPostAdminBot
    environment:
      - DATA_PATH=/var/NeoPostAdminBot
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
      - INITIAL_ADMIN_ID=${INITIAL_ADMIN_ID}
